name: Bug Report
description: Report a bug in spawn elytra
title: "Title..."
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Clearly describe what is wrong, what you did, and what you expected to happen.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Upload your logs to https://mclo.gs and paste the link here.
      placeholder: https://mclo.gs/xxxxxx
    validations:
      required: true
