name: Feature Request
description: Suggest a new feature or improvement for SpawnElytra
title: "Title..."
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: Clearly describe the feature or improvement you would like to see.
      placeholder: Describe the feature here...
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following before submitting
      options:
        - label: I have checked that this feature request does not already exist
          required: true
